"""
Financial health metrics analyzer for BankLens.

Computes core banking financial health KPIs from a transactions DataFrame:
    - Total Income (sum of Credit transactions)
    - Total Expenses (sum of Debit transactions excluding internal Savings transfers)
    - Savings Amount (Total Income - Total Expenses)
    - Savings Rate % (Savings Amount / Total Income * 100)
    - Expense-to-Income Ratio (Total Expenses / Total Income)
    - Top 3 Spending Categories (by total debit outlay)
    - Period covered by statement (e.g. '2024-01 to 2024-12')
    - Risk Profile (Low / Medium / High)
    - Financial Health Score (0-100)

Risk profile and health score are computed here, deterministically, rather than
being generated by the LLM. Both are pure functions of figures this module
already computes exactly, and a credit risk rating has to be reproducible and
auditable — an identical statement must always produce an identical rating. The
LLM's job downstream is to *explain* the rating it is given, not to decide it.
"""

from typing import Any, Literal
import pandas as pd
from pydantic import BaseModel, Field

from app.core.logger import get_logger

logger = get_logger(__name__)

RiskProfile = Literal["Low", "Medium", "High"]


# ── Risk Banding ──────────────────────────────────────────────────────────────
#
# Banded on savings rate alone. The original rule also carried an
# "or expense-to-income ratio > 85%" clause, which was dropped because it is
# both redundant and self-contradictory: expenses exclude internal savings
# transfers, so savings_rate_pct == 100 * (1 - expense_to_income_ratio) exactly.
# A ratio above 0.85 therefore *means* a savings rate below 15%, which overlaps
# the 10-30% Medium band and made customers between 10% and 15% simultaneously
# Medium and High. One monotone variable, three bands, no overlap.

RISK_LOW_MIN_SAVINGS_RATE = 30.0
RISK_MEDIUM_MIN_SAVINGS_RATE = 10.0

# Health score anchor points: (savings_rate_pct, score). Interpolated linearly
# between anchors and clamped to 0-100. Calibrated so the three reference
# archetypes land in their documented bands: a disciplined saver scores in the
# high 80s/90s, a solvent-but-stretched spender in the 60s/70s, and a customer
# in cashflow deficit in the 20s/30s.
HEALTH_SCORE_ANCHORS: list[tuple[float, float]] = [
    (-50.0, 25.0),
    (0.0, 50.0),
    (15.0, 68.0),
    (30.0, 75.0),
    (50.0, 85.0),
    (100.0, 98.0),
]


def compute_risk_profile(savings_rate_pct: float) -> RiskProfile:
    """
    Band a customer into Low / Medium / High credit risk by savings rate.

    Args:
        savings_rate_pct: Net savings as a percentage of income, 0-100 scale.
                          May be negative when the customer is in deficit.

    Returns:
        "Low" above 30%, "Medium" from 10% to 30%, "High" below 10%.
    """
    if savings_rate_pct >= RISK_LOW_MIN_SAVINGS_RATE:
        return "Low"
    if savings_rate_pct >= RISK_MEDIUM_MIN_SAVINGS_RATE:
        return "Medium"
    return "High"


def compute_health_score(savings_rate_pct: float) -> int:
    """
    Map savings rate to a 0-100 financial health score.

    Piecewise linear over HEALTH_SCORE_ANCHORS and monotonically increasing, so
    a customer who saves more can never score lower. Deliberately a function of
    one explainable variable — a score a Relationship Manager cannot explain to
    a customer is worse than no score at all.
    """
    anchors = HEALTH_SCORE_ANCHORS

    if savings_rate_pct <= anchors[0][0]:
        return int(round(anchors[0][1]))
    if savings_rate_pct >= anchors[-1][0]:
        return int(round(anchors[-1][1]))

    for (x0, y0), (x1, y1) in zip(anchors, anchors[1:]):
        if x0 <= savings_rate_pct <= x1:
            span = x1 - x0
            weight = (savings_rate_pct - x0) / span if span else 0.0
            return int(round(y0 + weight * (y1 - y0)))

    # Unreachable: the loop covers the full anchor range.
    return int(round(anchors[-1][1]))


# ── Essential vs Discretionary Classification ────────────────────────────────
#
# The profile narrative describes spending as essential or discretionary, and
# until now that split existed nowhere in the pipeline — the categorizer's
# vocabulary carries no such labels, so the LLM invented the mapping on every
# profile. The eval juror panel condemned exactly that claim, unanimously, in
# half the sampled cases: the one assertion in the product with no data behind
# it. The split is now computed here, from a hand classification of the
# categorizer's closed vocabulary, and the LLM is told the figures instead of
# being asked to imagine them.
#
# "Others" is deliberately in neither set. It is the categorizer's residual
# bucket, and calling unknown spending discretionary (or essential) would be
# the same invention this exists to remove. It is reported as unclassified.

ESSENTIAL_CATEGORIES: frozenset[str] = frozenset(
    {
        "Rent & Housing",
        "Food",
        "Utilities",
        "Transport",
        "Health",
        "Education",
        # Servicing existing debt is a fixed obligation, not a lifestyle
        # choice — and counting it as discretionary would understate exactly
        # the commitment that matters when judging capacity for more credit.
        "Debt Payments",
    }
)
DISCRETIONARY_CATEGORIES: frozenset[str] = frozenset({"Shopping", "Subscriptions"})

# Excluded from the split entirely: Savings is an internal transfer (already
# excluded from consumption expenses) and Income is a credit-side category.
NON_CONSUMPTION_CATEGORIES: frozenset[str] = frozenset({"Savings", "Income"})


# ── Output Data Model ─────────────────────────────────────────────────────────


class FinancialMetrics(BaseModel):
    """
    Validated financial metrics container passed downstream to RAG and LLM.

    Percentage fields are expressed on a 0–100 scale (e.g. 35.5 means 35.5%).
    """

    total_income: float
    total_expenses: float
    savings_amount: float
    savings_rate_pct: float
    expense_to_income_ratio: float

    # List of dicts: [{"category": "Food", "total_spent": 4500.0}, ...]
    top_categories: list[dict[str, Any]]

    transaction_count: int
    credit_count: int
    debit_count: int

    # Human-readable period string, e.g. "2024-03" or "2024-03 to 2024-05"
    period: str

    # ── Computed here, never generated by the LLM ─────────────────────────────
    risk_profile: RiskProfile
    financial_health_score: int = Field(ge=0, le=100)

    # Consumption expenses decomposed by the hand-classified category sets
    # above. unclassified_expenses is spending in "Others" (or any category
    # outside the known vocabulary): honestly unknown, not silently binned.
    # These exist so spending_pattern_breakdown is grounded in computed
    # figures rather than a split the model used to invent.
    essential_expenses: float
    discretionary_expenses: float
    unclassified_expenses: float

    # True when the customer spent more than they earned over the period.
    # This, not the risk band, is what gates unsecured credit recommendations:
    # a customer at 87% expenses is stretched but solvent, whereas one in
    # deficit is funding consumption from reserves or borrowing.
    is_cashflow_negative: bool


# ── Main Function ─────────────────────────────────────────────────────────────


def compute_metrics(df: pd.DataFrame) -> FinancialMetrics:
    """
    Compute financial health metrics from a categorized transactions DataFrame.

    Args:
        df: A pandas DataFrame with columns:
                date        (str or datetime) — transaction date
                description (str)             — merchant / memo
                amount      (float)           — always positive
                type        (str)             — 'Credit' or 'Debit'
                category    (str)             — assigned by categorizer

    Returns:
        A FinancialMetrics Pydantic model with all computed values.

    Raises:
        ValueError: If required columns are missing or the DataFrame is empty.
    """
    # ── Validate input ────────────────────────────────────────────────────────
    required_columns = {"date", "description", "amount", "type", "category"}
    missing = required_columns - set(df.columns)
    if missing:
        raise ValueError(
            f"Missing columns in uploaded CSV: {missing}. "
            "Expected: date, description, amount, type, category."
        )

    if df.empty:
        raise ValueError("The uploaded CSV contains no transactions.")

    # ── Split credits and debits ──────────────────────────────────────────────
    type_lower = df["type"].str.strip().str.lower()
    credits = df[type_lower == "credit"]
    debits = df[type_lower == "debit"]

    total_income = float(credits["amount"].sum())

    # Exclude internal savings/investment outlays from consumption expenses
    consumption_debits = debits[debits["category"] != "Savings"]
    total_expenses = (
        float(consumption_debits["amount"].sum())
        if not consumption_debits.empty
        else float(debits["amount"].sum())
    )
    savings_amount = total_income - total_expenses

    # Decompose consumption spending. Sums to total_expenses in the normal
    # case; in the degenerate all-debits-are-Savings fallback above the split
    # is legitimately all zeros while total_expenses is not.
    def _sum_for(categories: frozenset[str]) -> float:
        mask = consumption_debits["category"].isin(categories)
        return float(consumption_debits.loc[mask, "amount"].sum())

    essential_expenses = _sum_for(ESSENTIAL_CATEGORIES)
    discretionary_expenses = _sum_for(DISCRETIONARY_CATEGORIES)
    unclassified_expenses = float(
        consumption_debits.loc[
            ~consumption_debits["category"].isin(
                ESSENTIAL_CATEGORIES | DISCRETIONARY_CATEGORIES
            ),
            "amount",
        ].sum()
    )

    # Avoid division by zero for edge cases (e.g. statement with no income)
    if total_income > 0:
        savings_rate_pct = round(savings_amount / total_income * 100, 2)
        expense_to_income_ratio = round(total_expenses / total_income, 4)
    else:
        savings_rate_pct = 0.0
        expense_to_income_ratio = 0.0

    # ── Top 3 spending categories ─────────────────────────────────────────────
    category_totals = (
        debits.groupby("category")["amount"]
        .sum()
        .sort_values(ascending=False)
        .head(3)
        .reset_index()
        .rename(columns={"amount": "total_spent"})
    )
    top_categories: list[dict[str, Any]] = category_totals.to_dict(orient="records")

    # ── Determine the period covered by the statement ─────────────────────────
    df_temp = df.copy()
    df_temp["date"] = pd.to_datetime(df_temp["date"], errors="coerce")
    min_month = df_temp["date"].min().strftime("%Y-%m")
    max_month = df_temp["date"].max().strftime("%Y-%m")
    period = min_month if min_month == max_month else f"{min_month} to {max_month}"

    metrics = FinancialMetrics(
        total_income=total_income,
        total_expenses=total_expenses,
        savings_amount=savings_amount,
        savings_rate_pct=savings_rate_pct,
        expense_to_income_ratio=expense_to_income_ratio,
        top_categories=top_categories,
        transaction_count=len(df),
        credit_count=len(credits),
        debit_count=len(debits),
        period=period,
        essential_expenses=round(essential_expenses, 2),
        discretionary_expenses=round(discretionary_expenses, 2),
        unclassified_expenses=round(unclassified_expenses, 2),
        risk_profile=compute_risk_profile(savings_rate_pct),
        financial_health_score=compute_health_score(savings_rate_pct),
        is_cashflow_negative=savings_amount < 0,
    )

    logger.info(
        "Metrics computed | Period: %s | Income: %.2f | Expenses: %.2f | "
        "Savings Rate: %.2f%% | Expense Ratio: %.4f | Risk: %s | Score: %d",
        period,
        total_income,
        total_expenses,
        savings_rate_pct,
        expense_to_income_ratio,
        metrics.risk_profile,
        metrics.financial_health_score,
    )
    return metrics
